export enum ENV_ATTR {
  JWT_SECRET = 'JWT_SECRET',
  PORT = 'PORT',
  APP_URL = 'APP_URL',
  ELASTICSEARCH_NODE = 'ELASTICSEARCH_NODE',
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  HADOOP_URL = 'HADOOP_URL',
  HADOOP_PORT = 'HADOOP_PORT',
  HADOOP_PATH = 'HADOOP_PATH',
  HADOOP_HOST = 'HADOOP_HOST',
  HADOOP_HOST_USER = 'HADOOP_HOST_USER',
  HADOOP_LOCAL_PATH = 'HADOOP_LOCAL_PATH',
  CLIENT_URL = 'CLIENT_URL',

  // AI
  AI_URL = 'AI_URL',
}
